config/routes.rb
Myatm::Application.routes.draw do
  resources :banks

  resources :atms
  
    get "api/getbanks"
	
	get "api/getatm"
	get "api/getatmbycity"

end

app/models/atm.rb
class Atm < ActiveRecord::Base
end

app/models/bank.rb
class Bank < ActiveRecord::Base
end

app/controllers/api_controller.rb
class ApiController < ApplicationController


def getbanks()
	@banks=Bank.all;
	respond_to do |format|
        format.html # index.html.erb
        format.json { render :json => @banks}
        end
  end 
  
  def getatm()
	selectAtm((params[:bankid]))
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @query}
    end
  end 
  
  def getatmbycity()
	selectAtmByCity(params[:bankid],params[:city])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @query}
    end
  end 
  
  def selectAtm( bankid ="1")
		@query = Atm.where( bank: bankid) 
  end
  
  def selectAtmByCity (bankid ="1" , city ="a")
	@query = Atm.where( bank: bankid , city: city) 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/atms_controller.rb
class AtmsController < ApplicationController
  before_action :set_atm, only: [:show, :edit, :update, :destroy]

  # GET /atms
  # GET /atms.json
  def index
    @atms = Atm.all
  end

  # GET /atms/1
  # GET /atms/1.json
  def show
  end

  # GET /atms/new
  def new
    @atm = Atm.new
  end

  # GET /atms/1/edit
  def edit
  end

  # POST /atms
  # POST /atms.json
  def create
    @atm = Atm.new(atm_params)

    respond_to do |format|
      if @atm.save
        format.html { redirect_to @atm, notice: 'Atm was successfully created.' }
        format.json { render action: 'show', status: :created, location: @atm }
      else
        format.html { render action: 'new' }
        format.json { render json: @atm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /atms/1
  # PATCH/PUT /atms/1.json
  def update
    respond_to do |format|
      if @atm.update(atm_params)
        format.html { redirect_to @atm, notice: 'Atm was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @atm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /atms/1
  # DELETE /atms/1.json
  def destroy
    @atm.destroy
    respond_to do |format|
      format.html { redirect_to atms_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_atm
      @atm = Atm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def atm_params
      params.require(:atm).permit(:bank,:city , :longitude, :latitude, :address)
    end
end

app/controllers/banks_controller.rb
class BanksController < ApplicationController
  before_action :set_bank, only: [:show, :edit, :update, :destroy]

  # GET /banks
  # GET /banks.json
  def index
    @banks = Bank.all
  end

  # GET /banks/1
  # GET /banks/1.json
  def show
  end

  # GET /banks/new
  def new
    @bank = Bank.new
  end

  # GET /banks/1/edit
  def edit
  end

  # POST /banks
  # POST /banks.json
  def create
    @bank = Bank.new(bank_params)

    respond_to do |format|
      if @bank.save
        format.html { redirect_to @bank, notice: 'Bank was successfully created.' }
        format.json { render action: 'show', status: :created, location: @bank }
      else
        format.html { render action: 'new' }
        format.json { render json: @bank.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /banks/1
  # PATCH/PUT /banks/1.json
  def update
    respond_to do |format|
      if @bank.update(bank_params)
        format.html { redirect_to @bank, notice: 'Bank was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @bank.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /banks/1
  # DELETE /banks/1.json
  def destroy
    @bank.destroy
    respond_to do |format|
      format.html { redirect_to banks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bank
      @bank = Bank.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bank_params
      params.require(:bank).permit(:name, :icon, :website)
    end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/atms_helper.rb
module AtmsHelper
end

app/helpers/banks_helper.rb
module BanksHelper
end

app/views/atms/_form.html.erb
<%= form_for(@atm) do |f| %>
  <% if @atm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@atm.errors.count, "error") %> prohibited this atm from being saved:</h2>

      <ul>
      <% @atm.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :bank %><br>
    <%=  f.collection_select(:bank, Bank.all, :id, :name) %><br>
  </div>
   <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/atms/edit.html.erb
<h1>Editing atm</h1>

<%= render 'form' %>

<%= link_to 'Show', @atm %> |
<%= link_to 'Back', atms_path %>

app/views/atms/index.html.erb
<h1>Listing atms</h1>

<table>
  <thead>
    <tr>
      <th>Bank</th>
	  <th>City</th>
      <th>Longitude</th>
      <th>Latitude</th>
      <th>Address</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @atms.each do |atm| %>
      <tr>
        <td><%= Bank.find_by(id: (atm.bank).to_i ).name %></td>
		<td><%= atm.city %></td>
        <td><%= atm.longitude %></td>
        <td><%= atm.latitude %></td>
        <td><%= atm.address %></td>
        <td><%= link_to 'Show', atm %></td>
        <td><%= link_to 'Edit', edit_atm_path(atm) %></td>
        <td><%= link_to 'Destroy', atm, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Atm', new_atm_path %>

app/views/atms/new.html.erb
<h1>New atm</h1>

<%= render 'form' %>

<%= link_to 'Back', atms_path %>

app/views/atms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bank:</strong>
  <%= Bank.find_by(id: (@atm.bank).to_i ).name %>
</p>
<p>
  <strong>City:</strong>
  <%= @atm.city %>
</p>
<p>
  <strong>Longitude:</strong>
  <%= @atm.longitude %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @atm.latitude %>
</p>

<p>
  <strong>Address:</strong>
  <%= @atm.address %>
</p>

<%= link_to 'Edit', edit_atm_path(@atm) %> |
<%= link_to 'Back', atms_path %>

app/views/banks/_form.html.erb
<%= form_for(@bank) do |f| %>
  <% if @bank.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bank.errors.count, "error") %> prohibited this bank from being saved:</h2>

      <ul>
      <% @bank.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :icon %><br>
    <%= f.text_field :icon %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/banks/edit.html.erb
<h1>Editing bank</h1>

<%= render 'form' %>

<%= link_to 'Show', @bank %> |
<%= link_to 'Back', banks_path %>

app/views/banks/index.html.erb
<h1>Listing banks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Icon</th>
      <th>Website</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @banks.each do |bank| %>
      <tr>
        <td><%= bank.name %></td>
        <td><%= bank.icon %></td>
        <td><%= bank.website %></td>
        <td><%= link_to 'Show', bank %></td>
        <td><%= link_to 'Edit', edit_bank_path(bank) %></td>
        <td><%= link_to 'Destroy', bank, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bank', new_bank_path %>

app/views/banks/new.html.erb
<h1>New bank</h1>

<%= render 'form' %>

<%= link_to 'Back', banks_path %>

app/views/banks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @bank.name %>
</p>

<p>
  <strong>Icon:</strong>
  <%= @bank.icon %>
</p>

<p>
  <strong>Website:</strong>
  <%= @bank.website %>
</p>

<%= link_to 'Edit', edit_bank_path(@bank) %> |
<%= link_to 'Back', banks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myatm</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>